# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/molcluster',
                'doc_host': 'https://marcossantanaioc.github.io',
                'git_url': 'https://github.com/marcossantanaioc/molcluster',
                'lib_path': 'molcluster'},
  'syms': {'molcluster.core': {'molcluster.core.foo': ('core.html#foo', 'molcluster/core.py')}}}