# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"__all__": "typing_basics.ipynb",
         "BaseClustering": "clustering.ipynb",
         "KMeansClustering": "clustering.ipynb",
         "HDBSCANClustering": "clustering.ipynb",
         "ButinaClustering": "clustering.ipynb",
         "BaseTransform": "dimensionality_reduction.ipynb",
         "UMAPTransform": "dimensionality_reduction.ipynb",
         "PCATransform": "dimensionality_reduction.ipynb"}

modules = ["chem_basics.py",
           "unsupervised_learning/clustering.py",
           "unsupervised_learning/transform.py",
           "typing_basics.py"]

doc_url = "https://marcossantanaioc.github.io/molcluster/"

git_url = "https://github.com/marcossantanaioc/molcluster/tree/master/"

def custom_doc_links(name): return None
